### ISSUE TITLE
Help for register-user-profile.tfl

### ISSUE THREAD

**Issue by marziman** [3tav/MojECE.IdentityTheme#14]
Hello colleagues,

first of all many many thanks for your great work!
We used your valuable work to base our theme on top of it.
So we are now in the ChakraUI world. We are facing an issue on how we shall make the changes to render the `register-user-profile.ftl`.

We have added it to KcApp.tsx:
```
    case "register-user-profile.ftl":
      return <RegisterUserProfile {...{ kcContext, ...kcProps }} />
```

created a new folder under src > components > RegisterUserProfile > index.tsx

When we start and build it with yarn, we always see a white page. To find the mistake we pasted the .tsx code of a working page. So it is clear that we are unable to get the ChakraUI templated based version to run for `register-user-profile.ftl`

This is the page we want to include and customize with help of ChakraUI:
https://github.com/InseeFrLab/keycloakify/blob/v4.2.14-beta.0/src/lib/components/RegisterUserProfile.tsx

Can you somehow help us? We are not full experts in Keycloakify & ChakraUI and it is new for us.

Many thanks!

**Comment by markodvornik** [comment]
Hi.

Thanks for taking interest in this project, however we are not actively developing it anymore. We plan to test the new template system introduces in Keycloak 18 or to integrate deeper with the latest versions of `keycloakify`.

Firstly, I would recommend putting some `console.log` in the template to make sure it si beeing loaded at all.

`RegisterUserProfile` is not a part of this project since this project is based on an older version of `keycloakify` that doesn't include this template. To include `RegisterUserProfile` in our project codebase you need to follow the instructions on how to create custom pages.

I recomend [searching `keycloakify` repository](https://github.com/InseeFrLab/keycloakify/search?q=RegisterUserProfile) and examine all the files where `RegisterUserProfile` is used. 

Go through each file in the search resulsts and find coresponding setup in this repository and check if something is missing or is not defined. Note that folder structure and filenames in this repository are different than in the latest `keycloakify` repository.

 For example, compare `getKcContext` definitions in `/src/kcContext.ts`/ from this repo with [src/lib/getKcContext/KcContextBase.ts](https://github.com/InseeFrLab/keycloakify/blob/fc6328131fc7f45fd585bffd24bcf43bf1a42de6/src/lib/getKcContext/KcContextBase.ts#L143) from theirs. Did you define the template `register-user-profile.ftl`?

---

I will close this ticket, but feel free to post additional comment.
